### ISSUE TITLE
Fix 'Consider using localtime_r(...) instead of localtime(...) for improved thread safety.' issue in sakura_core\CBackupAgent.cpp

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#722]
[CodeFactor](https://www.codefactor.io/repository/github/sakura-editor/sakura) found an issue: Consider using localtime_r(...) instead of localtime(...) for improved thread safety.

It's currently on:
[sakura_core\CBackupAgent.cpp:369
](https://www.codefactor.io/repository/github/sakura-editor/sakura/source/master/sakura_core/CBackupAgent.cpp#L369)

**Comment by m-tmatma** [comment]
windows では  localtime_r は存在せず、独自関数が定義さているみたい。
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=vs-2017

**Comment by m-tmatma** [comment]
MinGW では localtime_r も localtime_s も存在しないみたい。
https://stackoverflow.com/questions/18551409/localtime-r-support-on-mingw

**Comment by berryzplus** [comment]
> MinGW では localtime_r も localtime_s も存在しないみたい。
> https://stackoverflow.com/questions/18551409/localtime-r-support-on-mingw

MinGW-w64には _s も _r も存在しているように見えます

```
C:\msys2\mingw64\lib\gcc\x86_64-w64-mingw32\8.2.0\adainclude\a-calend.adb(128,36)  [SJIS]:    --  NOTE: Targets which support localtime_r will aways return a historic
C:\msys2\mingw64\lib\gcc\x86_64-w64-mingw32\8.2.0\adainclude\a-calend.adb(130,8)  [SJIS]:    --  localtime_r operates.
C:\msys2\mingw64\x86_64-w64-mingw32\include\time.h(256,31)  [SJIS]: __forceinline errno_t __cdecl localtime_s(struct tm *_Tm,const time_t *_Time) { return _localtime32_s(_Tm,_Time); }
C:\msys2\mingw64\x86_64-w64-mingw32\include\time.h(261,31)  [SJIS]: __forceinline errno_t __cdecl localtime_s(struct tm *_Tm,const time_t *_Time) { return _localtime64_s(_Tm,_Time); }
C:\msys2\mingw64\x86_64-w64-mingw32\include\time.h(309,34)  [SJIS]: __forceinline struct tm *__cdecl localtime_r(const time_t *_Time, struct tm *_Tm) {
C:\msys2\mingw64\x86_64-w64-mingw32\include\time.h(310,10)  [SJIS]:   return localtime_s(_Tm, _Time) ? NULL : _Tm;
```

バージョンが古かったオチの可能性あるのかも。

**Comment by berryzplus** [comment]
'Consider using localtime_r(...) instead of localtime(...) for improved thread safety.'
`localtime`じゃなく`localtime_r`の方がスレッド安全なのでオススメです。（超約

シグニチャ
```c
struct tm *localtime_r(const time_t *timep, struct tm *result);
```

使ったことありませんが、引数は両方ともoutの気配がしますね・・・

⇒ [man page of CTIMEの日本語訳](https://linuxjm.osdn.jp/html/LDP_man-pages/man3/ctime.3.html)

マニュアル見ても使い方がわからんとはこれ如何に！ｗ


指摘のあった CBackupAgent.cpp:369 の周辺コード
https://github.com/sakura-editor/sakura/blob/cbf7c17c477dda9d53254d51f8d2163ca76c43f1/sakura_core/CBackupAgent.cpp#L365-L370


CodeFactorが何を言いたいのかぼんやりと把握しました。


 ------ この話についていくのに必要な情報ここまで ------


自作関数が必要かなぁ・・・
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=vs-2017

要するに、標準Cの`localtime`がグローバルの`time_t*`を使うのがマズいわけなので、
単に`_localtime64_s`に置換してやれば良い気がします。
（MinGW-w64でも使えそうなので）

**Comment by beru** [comment]
C11 に `localtime_s` はオプションであるけれど、C++11には無いみたいですね。
https://ja.cppreference.com/w/c/chrono/localtime

**Comment by m-tmatma** [comment]
#723 を投げました。

**Comment by ds14050** [comment]
今日読んでいた『Binary Hacks』に localtime のスレッドセイフティについて書かれていました。localtime_r は UNIX で定義されるようです。また Windows では _beginthreadex を呼び出すと自動的にスレッドで競合するグローバル変数ではなく TLS を使うようになるのでうらやましいなあ(※どこまで本心かは不明)、とも書かれていました。参考までに。

**Comment by berryzplus** [comment]
> 単に_localtime64_sに置換してやれば良い気がします。

全力で突っ込み待ちだったんですが :smile:

**Comment by m-tmatma** [comment]
> > 単に_localtime64_sに置換してやれば良い気がします。
> 
> 全力で突っ込み待ちだったんですが 😄

MinGW でも使えるのでそうしました。
